### ISSUE TITLE
Would it be posible to access your design files?

### ISSUE THREAD

**Issue by KeLaiFu** [Testbild-synth/Hagiwo_009_030_sequencer#1]
First of all, thanks for making the Hagiwo modules accessable to those of us too lazy to use veroboard, really happy to see them being upped to github.

I have just ordred a few of his modules from another chap doing the same and in the process I edited them a little, just to make the jack spacing and screen height etc the same as some of my current modules in the rack. A bit of a first world OCD problem I know, but would it be posible to get the kicad/eagle files of the ones you made added to the repo so I could do the same and keep everthing in the same style?

**Comment by Testbild-synth** [comment]
Hey :) So I use easyeda for my pcbs and inkscape for my panels. The panels I can give you either as an inkscape project file or converted to a kicad project, for the pcbs I have too look what the best way to export them is. I think easyeda does kicad and eagle export but I've tried it once and it seemed a bit buggy. with that in mind, what do you think is the best format to upload the design files

edit: so easyeda does NOT have kicad/eagle export but there are online converters wher you can dump board files in apparently. Not sure how useful these are but I can try

**Comment by KeLaiFu** [comment]
I've used the web based easyeda > kicad converter without problems, so just uploading your files without any changes should be fine.

**Comment by Testbild-synth** [comment]
ok good to know. I will upload the files today after work

**Comment by Testbild-synth** [comment]
@KeLaiFu I uploaded all the files, check again and if these are helpful for you I can close the issue

**Comment by KeLaiFu** [comment]
I had a quick look as I am on my way out of the house, looks fine, thanks so much!
