### ISSUE TITLE
Gerber and Production file mismatch

### ISSUE THREAD

**Issue by DeadPanne** [Testbild-synth/Hagiwo_009_030_sequencer#2]
To start, Thank you for your amazing work on the HAGIWO designs!
I was planning on doing some modification of the PCB, but when looking at the design files for this repo, it seems like you've uploaded the production files for the [Eurorack Quantizer](https://github.com/Testbild-synth/HAGIWO-029-033-Eurorack-quantizer) as it uses a Seeeduino Xiao in the PCB

Thanks in advance

**Comment by Testbild-synth** [comment]
ok sorry, I uploaded multiple projects these last few days and must have gotten confused. now it should be fine

**Comment by Testbild-synth** [comment]
i will close this for now, if I made another mistake just tell me
